
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kkube.kkube.kni.io
  resources:
  - openshiftclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kkube.kkube.kni.io
  resources:
  - openshiftclusters/finalizers
  verbs:
  - update
- apiGroups:
  - kkube.kkube.kni.io
  resources:
  - openshiftclusters/status
  verbs:
  - get
  - patch
  - update
