apiVersion: openshift.kkube.kni.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  masters: 
    virtaul: 3
  workers: 
    physical: 2
  version: "4.10"
  networkType: OVN
  disconnected: false
  keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWWipbX819wFCM75f1J1Gr0IDZm1A5rPxFemibbGVboUwA2La/Msf9Oa9hLSnq1PEpT2VB+KysjCggA4semrXR85VctExW8mBPDgG6uLCnmQ9f/Vtkg0GEfR4mkuCxBVxPV8OVTeU4Lv2kAEcBGJEwStQei0/1u24Y4b9njCe0kYY1rJvn1XNAab1avDMAr1AVrV4jx+ChrZtZsoN/CQxWfeFFYEgyzg00wmq5QKanOcraKNZAg93sRK48QiW21EHCO0iJXiArZonhwSNUoiprqreK1666xRDCCzM9mu8/gQl7XV9za713KkNMeKdGKRR9nGl3BhZshwd4+dPNQboUPGwZXwU9IoecFVSjfBZkhYupdcQXHfWQ58ZqX9i90b4Xq+INqVk4rOIyplf3FWMb/xXnl+mNX3f7T7SPETdVVhlHKCDslmffGC4PDuZF8UIlKahnt5T2WWE4NRzCHsNQyxqVJi4at7/9U+nYa4oeha/QB4s+07N/q+LD1PVLOws= tali@Taos-MacBook-Pro
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1+R3ze1Li5nqIuwUovSJpgZugxsGiN/Tx2ICti+l+WXLRgCW3lzQ4CqfT7AuvYe0ht7au2TbNKmV8CjkUjDf/pwUGjPAOIA+FL2abEwTEjo+YXWoRlwdX+sx+s5YVEbjyvfQ1sqahzpQDHG7k2vl741gwWpTqEjxbm/V2YUDG9OQVgJrR/IOiAzAGdaJQs5kZJK1G0ep8s0ONzOIu/8Q98YDwb26BV0OnCOY+/gBKhJw7RLXaDKqILx/U3BunH3OwcAY8cZixCwWZpJqaq6wbt4uX3RWIoiuyfi4jfFSigNltMdX18tDgv8G+GxHoFsOoj7Gwu9VGrwu6R0CmFg9T shintasugimoto@MacBook-Pro
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7gT5k7+T0HO4DZK41E7BySG+wkzhv+A3B7/0Mu4ui0Re3FBAQwKA/UXe6iDBdkR6+NA37bTrfufJ63P/zqKwQUrdo1xmxm30QVumwyxz57ylGW8aI/P2mH8ukjDRv88UWkg36eS6GjewSp/4SYjNi/osOlbcRVaGs6f0ikK6ukK+PShP//X6vdVhEuf+f4zmzo192OpNOuLsrx24nqc+Qc9yIJnTO0zpqt6ZE0OdswsGW+/8dPgGiTIrGyMF59MaaDcz3iinsqb9FmJzgVG/YA9ZzSgqk/Zu2H+1SB6l8NudqP8L5pIDdOxM/Kpp8OQhlhD4BP/NBhDebWOa/xpRJ0LYciUcyv+wBUhtb6WnMJiTZzjnO++UgoHqU1NAPBJc9jzYt5oukZb9sUp8rDDHx+qLxHBcVQ/JBvS3pdqeCCIfsHxuLkCJGdj89KfTv1CxavWNBUNMyUzyGvjsF5H1KhmYQ+KuJI3geuK1eDNQbLRAmTg0H3pNsJLUJ/8H2AtM= mgourin@mgourin.tlv.csb
status:
  domain: lab.kni.com
  apiVIP: 1.1.1.1
  ingressVIP: 2.2.2.2
  masters:
    virtual:
    - aa:aa:aa:aa:aa:00
    - aa:aa:aa:aa:aa:01
    - aa:aa:aa:aa:aa:02
  workers:
    physical:
    - redfish_address: 1.1.1.2
      model: dell
      provisioning_mac: AA:BB:CC:DD:EE:FF
      bmc_user: root
      bmc_password: calvin
    - redfish_address: 1.1.1.3
      model: dell
      provisioning_mac: AA:BB:CC:DD:EE:00
      bmc_user: root
      bmc_password: calvin
